name: Image Docker Checks & Schedules

# Define events that trigger the workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours at 0 minutes past the hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Build the Docker image with a timestamp tag
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
